package ru.miacomsoft.EasyWebServer.component;

import ru.miacomsoft.EasyWebServer.HttpExchange;

/**
 * JavaScript библиотека для компонента cmpAction
 * Подключается автоматически при наличии cmpAction на странице
 */
public class cmpAction_js {

    public static byte[] onPage(HttpExchange query) {
        query.mimeType = "application/javascript";

        StringBuffer sb = new StringBuffer();
        sb.append("/**\n");
        sb.append(" * JavaScript библиотека для компонента cmpAction\n");
        sb.append(" * Предоставляет методы для работы с действиями на клиенте\n");
        sb.append(" */\n");
        sb.append("(function() {\n");
        sb.append("    // Предотвращаем повторную инициализацию\n");
        sb.append("    if (window.cmpActionInitialized) return;\n");
        sb.append("    window.cmpActionInitialized = true;\n");
        sb.append("\n");
        sb.append("    console.log('cmpAction: JavaScript library initialized');\n");
        sb.append("\n");
        sb.append("    /**\n");
        sb.append("     * Расширение D3Api для работы с действиями\n");
        sb.append("     */\n");
        sb.append("    if (typeof D3Api !== 'undefined') {\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Установка автоматического действия\n");
        sb.append("         * @param {string} name - Имя действия\n");
        sb.append("         */\n");
        sb.append("        D3Api.setActionAuto = function(name) {\n");
        sb.append("            if (!this.GLOBAL_ACTION) this.GLOBAL_ACTION = {};\n");
        sb.append("            this.GLOBAL_ACTION[name] = {};\n");
        sb.append("        };\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Выполнение действия\n");
        sb.append("         * @param {string} nameAction - Имя действия\n");
        sb.append("         * @param {Function} callBack - Функция обратного вызова\n");
        sb.append("         */\n");
        sb.append("        D3Api.executeAction = function(nameAction, callBack) {\n");
        sb.append("            return executeAction(nameAction, callBack);\n");
        sb.append("        };\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Получение результата действия\n");
        sb.append("         * @param {string} nameAction - Имя действия\n");
        sb.append("         * @returns {Object} - Результат действия\n");
        sb.append("         */\n");
        sb.append("        D3Api.getActionResult = function(nameAction) {\n");
        sb.append("            if (this.GLOBAL_ACTION && this.GLOBAL_ACTION[nameAction]) {\n");
        sb.append("                return this.GLOBAL_ACTION[nameAction];\n");
        sb.append("            }\n");
        sb.append("            return null;\n");
        sb.append("        };\n");
        sb.append("    }\n");
        sb.append("\n");
        sb.append("    /**\n");
        sb.append("     * Инициализация всех действий на странице\n");
        sb.append("     */\n");
        sb.append("    function initActions() {\n");
        sb.append("        var actionElements = document.querySelectorAll('[schema=\"Action\"]');\n");
        sb.append("        for (var i = 0; i < actionElements.length; i++) {\n");
        sb.append("            var actionEl = actionElements[i];\n");
        sb.append("            var name = actionEl.getAttribute('name');\n");
        sb.append("            if (name && window.D3Api) {\n");
        sb.append("                D3Api.setActionAuto(name);\n");
        sb.append("                console.log('cmpAction: Auto-initialized action:', name);\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("    }\n");
        sb.append("\n");
        sb.append("    /**\n");
        sb.append("     * Глобальная функция выполнения действия\n");
        sb.append("     * @param {string} nameAction - Имя действия\n");
        sb.append("     * @param {Function} callBack - Функция обратного вызова\n");
        sb.append("     */\n");
        sb.append("    window.executeAction = function(nameAction, callBack) {\n");
        sb.append("        var ctrlObj = document.querySelector('[name=\"' + nameAction + '\"]');\n");
        sb.append("        if (!ctrlObj) {\n");
        sb.append("            console.error('Action not found:', nameAction);\n");
        sb.append("            return;\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        // Получаем атрибуты\n");
        sb.append("        var varsString = ctrlObj.getAttribute('vars');\n");
        sb.append("        console.log('Raw vars string:', varsString);\n");
        sb.append("\n");
        sb.append("        // Парсим vars\n");
        sb.append("        var jsonVars = {};\n");
        sb.append("\n");
        sb.append("        try {\n");
        sb.append("            var fixedString = varsString\n");
        sb.append("                .replace(/'/g, '\"')\n");
        sb.append("                .replace(/(\\w+):/g, '\"$1\":')\n");
        sb.append("                .replace(/,\\s*}/g, '}');\n");
        sb.append("\n");
        sb.append("            console.log('Fixed string:', fixedString);\n");
        sb.append("            jsonVars = JSON.parse(fixedString);\n");
        sb.append("        } catch (e) {\n");
        sb.append("            console.log('JSON parse failed, trying manual parse:', e);\n");
        sb.append("\n");
        sb.append("            try {\n");
        sb.append("                var cleanStr = varsString.trim();\n");
        sb.append("                if (cleanStr.startsWith('{') && cleanStr.endsWith('}')) {\n");
        sb.append("                    cleanStr = cleanStr.substring(1, cleanStr.length - 1);\n");
        sb.append("                }\n");
        sb.append("\n");
        sb.append("                var pairs = [];\n");
        sb.append("                var depth = 0;\n");
        sb.append("                var current = '';\n");
        sb.append("\n");
        sb.append("                for (var i = 0; i < cleanStr.length; i++) {\n");
        sb.append("                    var c = cleanStr[i];\n");
        sb.append("\n");
        sb.append("                    if (c === '{') depth++;\n");
        sb.append("                    else if (c === '}') depth--;\n");
        sb.append("\n");
        sb.append("                    if (c === ',' && depth === 0) {\n");
        sb.append("                        pairs.push(current);\n");
        sb.append("                        current = '';\n");
        sb.append("                    } else {\n");
        sb.append("                        current += c;\n");
        sb.append("                    }\n");
        sb.append("                }\n");
        sb.append("                if (current.trim()) {\n");
        sb.append("                    pairs.push(current);\n");
        sb.append("                }\n");
        sb.append("\n");
        sb.append("                for (var p = 0; p < pairs.length; p++) {\n");
        sb.append("                    var pair = pairs[p];\n");
        sb.append("                    var colonIndex = pair.indexOf(':');\n");
        sb.append("                    if (colonIndex === -1) continue;\n");
        sb.append("\n");
        sb.append("                    var key = pair.substring(0, colonIndex).trim().replace(/['\"]/g, '');\n");
        sb.append("                    var valueStr = pair.substring(colonIndex + 1).trim();\n");
        sb.append("\n");
        sb.append("                    if (valueStr.startsWith('{') && valueStr.endsWith('}')) {\n");
        sb.append("                        var obj = {};\n");
        sb.append("                        var innerStr = valueStr.substring(1, valueStr.length - 1);\n");
        sb.append("                        var innerPairs = innerStr.split(',');\n");
        sb.append("\n");
        sb.append("                        for (var inner = 0; inner < innerPairs.length; inner++) {\n");
        sb.append("                            var innerPair = innerPairs[inner];\n");
        sb.append("                            var innerColon = innerPair.indexOf(':');\n");
        sb.append("                            if (innerColon === -1) continue;\n");
        sb.append("\n");
        sb.append("                            var innerKey = innerPair.substring(0, innerColon).trim().replace(/['\"]/g, '');\n");
        sb.append("                            var innerValue = innerPair.substring(innerColon + 1).trim().replace(/['\"]/g, '');\n");
        sb.append("                            obj[innerKey] = innerValue;\n");
        sb.append("                        }\n");
        sb.append("                        jsonVars[key] = obj;\n");
        sb.append("                    }\n");
        sb.append("                }\n");
        sb.append("\n");
        sb.append("                console.log('Manually parsed vars:', jsonVars);\n");
        sb.append("            } catch (e2) {\n");
        sb.append("                console.error('Manual parse failed:', e2);\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        var query_type = ctrlObj.getAttribute('query_type') || 'java';\n");
        sb.append("        var action_name = ctrlObj.getAttribute('action_name');\n");
        sb.append("\n");
        sb.append("        console.log('Action info:', {query_type, action_name});\n");
        sb.append("        console.log('Parsed vars:', jsonVars);\n");
        sb.append("\n");
        sb.append("        // Формируем данные для отправки\n");
        sb.append("        var requestData = {};\n");
        sb.append("\n");
        sb.append("        for (var key in jsonVars) {\n");
        sb.append("            var varInfo = jsonVars[key];\n");
        sb.append("            if (!varInfo) continue;\n");
        sb.append("\n");
        sb.append("            var value = '';\n");
        sb.append("            var src = varInfo.src || key;\n");
        sb.append("            var srctype = varInfo.srctype || 'var';\n");
        sb.append("            var defaultVal = varInfo.defaultVal || '';\n");
        sb.append("            var len = varInfo.len || '';\n");
        sb.append("\n");
        sb.append("            if (srctype === 'var') {\n");
        sb.append("                value = window.getVar ? window.getVar(src) || defaultVal : defaultVal;\n");
        sb.append("            } else if (srctype === 'ctrl') {\n");
        sb.append("                if (window.D3Api && D3Api.getValue) {\n");
        sb.append("                    value = D3Api.getValue(src) || defaultVal;\n");
        sb.append("                } else {\n");
        sb.append("                    var ctrlElement = document.querySelector('[name=\"' + src + '\"]');\n");
        sb.append("                    value = ctrlElement ? ctrlElement.value : defaultVal;\n");
        sb.append("                }\n");
        sb.append("            } else if (srctype === 'session') {\n");
        sb.append("                value = defaultVal;\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            requestData[key] = {\n");
        sb.append("                'srctype': srctype,\n");
        sb.append("                'src': src,\n");
        sb.append("                'value': String(value),\n");
        sb.append("                'defaultVal': defaultVal\n");
        sb.append("            };\n");
        sb.append("\n");
        sb.append("            if (len) {\n");
        sb.append("                requestData[key].len = len;\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("\n");
        sb.append("        console.log('Sending request data:', requestData);\n");
        sb.append("        console.log('URL:', '/{component}/cmpAction?query_type=' + query_type + '&action_name=' + action_name);\n");
        sb.append("\n");
        sb.append("        fetch('/{component}/cmpAction?query_type=' + query_type + '&action_name=' + action_name, {\n");
        sb.append("            method: 'POST',\n");
        sb.append("            headers: {\n");
        sb.append("                'Content-Type': 'application/json'\n");
        sb.append("            },\n");
        sb.append("            body: JSON.stringify(requestData)\n");
        sb.append("        })\n");
        sb.append("        .then(function(response) {\n");
        sb.append("            return response.json();\n");
        sb.append("        })\n");
        sb.append("        .then(function(dataObj) {\n");
        sb.append("            console.log('Response received:', dataObj);\n");
        sb.append("\n");
        sb.append("            if (dataObj.redirect) {\n");
        sb.append("                if (window.saveDirect) {\n");
        sb.append("                    window.saveDirect('loginDirect');\n");
        sb.append("                }\n");
        sb.append("                window.location.href = dataObj.redirect;\n");
        sb.append("                return;\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            if (dataObj.ERROR) {\n");
        sb.append("                console.error('Action error:', dataObj.ERROR);\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            // Обрабатываем выходные переменные\n");
        sb.append("            if (dataObj.vars) {\n");
        sb.append("                var data = dataObj.vars;\n");
        sb.append("                for (var key in data) {\n");
        sb.append("                    var varInfo = data[key];\n");
        sb.append("                    if (typeof varInfo === 'object') {\n");
        sb.append("                        var value = varInfo.value;\n");
        sb.append("                        var srctype = varInfo.srctype || 'var';\n");
        sb.append("                        var src = varInfo.src || key;\n");
        sb.append("\n");
        sb.append("                        if (value === 'null') value = null;\n");
        sb.append("                        else if (value === 'true') value = true;\n");
        sb.append("                        else if (value === 'false') value = false;\n");
        sb.append("\n");
        sb.append("                        console.log('Setting output:', {key, srctype, src, value});\n");
        sb.append("\n");
        sb.append("                        if (srctype === 'var') {\n");
        sb.append("                            if (window.setVar) {\n");
        sb.append("                                window.setVar(src, value);\n");
        sb.append("                            }\n");
        sb.append("                        } else if (srctype === 'ctrl') {\n");
        sb.append("                            if (value === null) value = '';\n");
        sb.append("                            if (window.D3Api && D3Api.setValue) {\n");
        sb.append("                                D3Api.setValue(src, value);\n");
        sb.append("                            } else {\n");
        sb.append("                                var targetElement = document.querySelector('[name=\"' + src + '\"]');\n");
        sb.append("                                if (targetElement) targetElement.value = value;\n");
        sb.append("                            }\n");
        sb.append("                        }\n");
        sb.append("                    }\n");
        sb.append("                }\n");
        sb.append("            }\n");
        sb.append("\n");
        sb.append("            if (!window.D3Api || !D3Api.GLOBAL_ACTION) {\n");
        sb.append("                window.D3Api = window.D3Api || {};\n");
        sb.append("                D3Api.GLOBAL_ACTION = D3Api.GLOBAL_ACTION || {};\n");
        sb.append("            }\n");
        sb.append("            \n");
        sb.append("            D3Api.GLOBAL_ACTION[nameAction] = dataObj;\n");
        sb.append("\n");
        sb.append("            if (callBack && typeof callBack === 'function') {\n");
        sb.append("                callBack(dataObj.vars || {});\n");
        sb.append("            }\n");
        sb.append("        })\n");
        sb.append("        .catch(function(error) {\n");
        sb.append("            console.error('Fetch error:', error);\n");
        sb.append("        });\n");
        sb.append("    };\n");
        sb.append("\n");
        sb.append("    // Инициализация после загрузки DOM\n");
        sb.append("    if (document.readyState === 'loading') {\n");
        sb.append("        document.addEventListener('DOMContentLoaded', initActions);\n");
        sb.append("    } else {\n");
        sb.append("        initActions();\n");
        sb.append("    }\n");
        sb.append("})();\n");

        return sb.toString().getBytes();
    }
}