package ru.miacomsoft.EasyWebServer.component;

import ru.miacomsoft.EasyWebServer.HttpExchange;

/**
 * JavaScript библиотека для компонента cmpButton
 * Подключается автоматически при наличии cmpButton на странице
 * Расширяет функционал D3Api для работы с кнопками
 */
public class cmpButton_js {

    public static byte[] onPage(HttpExchange query) {
        query.mimeType = "application/javascript";

        StringBuffer sb = new StringBuffer();
        sb.append("/**\n");
        sb.append(" * JavaScript библиотека для компонента cmpButton\n");
        sb.append(" * Расширяет функционал D3Api для работы с кнопками\n");
        sb.append(" * Подключается автоматически при наличии cmpButton на странице\n");
        sb.append(" */\n");
        sb.append("(function() {\n");
        sb.append("    // Предотвращаем повторную инициализацию\n");
        sb.append("    if (window.cmpButtonInitialized) return;\n");
        sb.append("    window.cmpButtonInitialized = true;\n");
        sb.append("\n");
        sb.append("    console.log('cmpButton: JavaScript library initialized');\n");
        sb.append("\n");
        sb.append("    // Хранилище для обработчиков событий\n");
        sb.append("    var buttonClickHandlers = {};\n");
        sb.append("\n");
        sb.append("    /**\n");
        sb.append("     * Инициализация всех кнопок на странице\n");
        sb.append("     */\n");
        sb.append("    function initButtons() {\n");
        sb.append("        var buttons = document.querySelectorAll('[schema=\"Action\"]');\n");
        sb.append("        console.log('cmpButton: Found ' + buttons.length + ' buttons');\n");
        sb.append("        \n");
        sb.append("        for (var i = 0; i < buttons.length; i++) {\n");
        sb.append("            var button = buttons[i];\n");
        sb.append("            var name = button.getAttribute('name');\n");
        sb.append("            var actionName = button.getAttribute('action_name');\n");
        sb.append("            \n");
        sb.append("            if (name) {\n");
        sb.append("                // Добавляем обработчик клика\n");
        sb.append("                button.addEventListener('click', function(e) {\n");
        sb.append("                    var btn = e.target;\n");
        sb.append("                    var name = btn.getAttribute('name');\n");
        sb.append("                    var actionName = btn.getAttribute('action_name');\n");
        sb.append("                    \n");
        sb.append("                    console.log('cmpButton: Button \"' + name + '\" clicked');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие клика\n");
        sb.append("                    var event = new CustomEvent('buttonClick', {\n");
        sb.append("                        detail: { \n");
        sb.append("                            name: name,\n");
        sb.append("                            actionName: actionName,\n");
        sb.append("                            button: btn\n");
        sb.append("                        },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    btn.dispatchEvent(event);\n");
        sb.append("                    \n");
        sb.append("                    // Вызываем пользовательский обработчик если есть\n");
        sb.append("                    if (buttonClickHandlers[name]) {\n");
        sb.append("                        buttonClickHandlers[name](btn);\n");
        sb.append("                    }\n");
        sb.append("                });\n");
        sb.append("                \n");
        sb.append("                // Добавляем обработчик наведения\n");
        sb.append("                button.addEventListener('mouseenter', function(e) {\n");
        sb.append("                    var btn = e.target;\n");
        sb.append("                    var name = btn.getAttribute('name');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие наведения\n");
        sb.append("                    var event = new CustomEvent('buttonHover', {\n");
        sb.append("                        detail: { name: name },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    btn.dispatchEvent(event);\n");
        sb.append("                });\n");
        sb.append("                \n");
        sb.append("                // Добавляем обработчик ухода мыши\n");
        sb.append("                button.addEventListener('mouseleave', function(e) {\n");
        sb.append("                    var btn = e.target;\n");
        sb.append("                    var name = btn.getAttribute('name');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие ухода мыши\n");
        sb.append("                    var event = new CustomEvent('buttonLeave', {\n");
        sb.append("                        detail: { name: name },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    btn.dispatchEvent(event);\n");
        sb.append("                });\n");
        sb.append("                \n");
        sb.append("                // Добавляем обработчик фокуса\n");
        sb.append("                button.addEventListener('focus', function(e) {\n");
        sb.append("                    var btn = e.target;\n");
        sb.append("                    var name = btn.getAttribute('name');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие фокуса\n");
        sb.append("                    var event = new CustomEvent('buttonFocus', {\n");
        sb.append("                        detail: { name: name },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    btn.dispatchEvent(event);\n");
        sb.append("                });\n");
        sb.append("                \n");
        sb.append("                // Добавляем обработчик потери фокуса\n");
        sb.append("                button.addEventListener('blur', function(e) {\n");
        sb.append("                    var btn = e.target;\n");
        sb.append("                    var name = btn.getAttribute('name');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие потери фокуса\n");
        sb.append("                    var event = new CustomEvent('buttonBlur', {\n");
        sb.append("                        detail: { name: name },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    btn.dispatchEvent(event);\n");
        sb.append("                });\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("    }\n");
        sb.append("\n");
        sb.append("    /**\n");
        sb.append("     * Расширение D3Api для работы с кнопками\n");
        sb.append("     */\n");
        sb.append("    if (typeof D3Api !== 'undefined') {\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Установка обработчика клика на кнопку\n");
        sb.append("         * @param {string} name - Имя кнопки\n");
        sb.append("         * @param {Function} handler - Функция обработчик\n");
        sb.append("         */\n");
        sb.append("        D3Api.onClick = function(name, handler) {\n");
        sb.append("            if (typeof handler !== 'function') return;\n");
        sb.append("            \n");
        sb.append("            var button = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("            if (button) {\n");
        sb.append("                buttonClickHandlers[name] = handler;\n");
        sb.append("                console.log('cmpButton: Click handler set for', name);\n");
        sb.append("            }\n");
        sb.append("        };\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Удаление обработчика клика с кнопки\n");
        sb.append("         * @param {string} name - Имя кнопки\n");
        sb.append("         */\n");
        sb.append("        D3Api.offClick = function(name) {\n");
        sb.append("            if (buttonClickHandlers[name]) {\n");
        sb.append("                delete buttonClickHandlers[name];\n");
        sb.append("                console.log('cmpButton: Click handler removed for', name);\n");
        sb.append("            }\n");
        sb.append("        };\n");
        sb.append("        \n");
        sb.append("        // Алиас для обратной совместимости\n");
        sb.append("        D3Api.onButtonClick = D3Api.onClick;\n");
        sb.append("    }\n");
        sb.append("\n");
        sb.append("    // Инициализация после загрузки DOM\n");
        sb.append("    if (document.readyState === 'loading') {\n");
        sb.append("        document.addEventListener('DOMContentLoaded', function() {\n");
        sb.append("            initButtons();\n");
        sb.append("            \n");
        sb.append("            // Добавляем расширения в существующие методы D3Api\n");
        sb.append("            if (typeof D3Api !== 'undefined') {\n");
        sb.append("                // Сохраняем оригинальные методы если они существуют\n");
        sb.append("                var originalSetCaption = D3Api.setCaption;\n");
        sb.append("                var originalGetCaption = D3Api.getCaption;\n");
        sb.append("                var originalSetDisabled = D3Api.setDisabled;\n");
        sb.append("                \n");
        sb.append("                // Расширяем setCaption для работы с кнопками\n");
        sb.append("                D3Api.setCaption = function(name, text) {\n");
        sb.append("                    // Проверяем, является ли контрол кнопкой\n");
        sb.append("                    var ctrl = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("                    if (ctrl && ctrl.getAttribute('schema') === 'Action') {\n");
        sb.append("                        // Для кнопок используем textContent\n");
        sb.append("                        ctrl.textContent = text;\n");
        sb.append("                        \n");
        sb.append("                        // Генерируем событие изменения\n");
        sb.append("                        var event = new CustomEvent('captionChanged', {\n");
        sb.append("                            detail: { name: name, newText: text },\n");
        sb.append("                            bubbles: true\n");
        sb.append("                        });\n");
        sb.append("                        ctrl.dispatchEvent(event);\n");
        sb.append("                        \n");
        sb.append("                        return true;\n");
        sb.append("                    } else {\n");
        sb.append("                        // Для других контролов используем оригинальный метод\n");
        sb.append("                        if (originalSetCaption) {\n");
        sb.append("                            return originalSetCaption.call(D3Api, name, text);\n");
        sb.append("                        }\n");
        sb.append("                    }\n");
        sb.append("                    return false;\n");
        sb.append("                };\n");
        sb.append("                \n");
        sb.append("                // Расширяем getCaption для работы с кнопками\n");
        sb.append("                D3Api.getCaption = function(name) {\n");
        sb.append("                    // Проверяем, является ли контрол кнопкой\n");
        sb.append("                    var ctrl = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("                    if (ctrl && ctrl.getAttribute('schema') === 'Action') {\n");
        sb.append("                        return ctrl.textContent;\n");
        sb.append("                    } else {\n");
        sb.append("                        // Для других контролов используем оригинальный метод\n");
        sb.append("                        if (originalGetCaption) {\n");
        sb.append("                            return originalGetCaption.call(D3Api, name);\n");
        sb.append("                        }\n");
        sb.append("                    }\n");
        sb.append("                    return null;\n");
        sb.append("                };\n");
        sb.append("                \n");
        sb.append("                // Расширяем setDisabled для работы с easyui классами\n");
        sb.append("                D3Api.setDisabled = function(name, bool) {\n");
        sb.append("                    bool = (bool == true);\n");
        sb.append("                    var ctrl = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("                    if (!ctrl) return false;\n");
        sb.append("                    \n");
        sb.append("                    // Проверяем, является ли контрол кнопкой easyui\n");
        sb.append("                    if (ctrl.classList.contains('easyui-linkbutton')) {\n");
        sb.append("                        if (bool) {\n");
        sb.append("                            ctrl.setAttribute('disabled', 'disabled');\n");
        sb.append("                            ctrl.classList.add('ui-state-disabled');\n");
        sb.append("                        } else {\n");
        sb.append("                            ctrl.removeAttribute('disabled');\n");
        sb.append("                            ctrl.classList.remove('ui-state-disabled', 'ui-button-disabled');\n");
        sb.append("                        }\n");
        sb.append("                        return true;\n");
        sb.append("                    } else {\n");
        sb.append("                        // Для других контролов используем оригинальный метод\n");
        sb.append("                        if (originalSetDisabled) {\n");
        sb.append("                            return originalSetDisabled.call(D3Api, name, bool);\n");
        sb.append("                        }\n");
        sb.append("                    }\n");
        sb.append("                    return false;\n");
        sb.append("                };\n");
        sb.append("                \n");
        sb.append("                // Добавляем удобные методы-алиасы\n");
        sb.append("                D3Api.setEnabled = function(name, bool) {\n");
        sb.append("                    return this.setDisabled(name, !bool);\n");
        sb.append("                };\n");
        sb.append("                \n");
        sb.append("                console.log('cmpButton: D3Api extended with button functionality');\n");
        sb.append("            }\n");
        sb.append("        });\n");
        sb.append("    } else {\n");
        sb.append("        initButtons();\n");
        sb.append("    }\n");
        sb.append("})();\n");

        return sb.toString().getBytes();
    }
}