package ru.miacomsoft.EasyWebServer.component;

import ru.miacomsoft.EasyWebServer.HttpExchange;

/**
 * JavaScript библиотека для компонента cmpEdit
 * Подключается автоматически при наличии cmpEdit на странице
 * Предоставляет базовые методы для работы с полями ввода
 */
public class cmpEdit_js {

    public static byte[] onPage(HttpExchange query) {
        query.mimeType = "application/javascript";

        StringBuffer sb = new StringBuffer();
        sb.append("/**\n");
        sb.append(" * JavaScript библиотека для компонента cmpEdit\n");
        sb.append(" * Предоставляет базовые методы для работы с полями ввода\n");
        sb.append(" * Подключается автоматически при наличии cmpEdit на странице\n");
        sb.append(" */\n");
        sb.append("(function() {\n");
        sb.append("    // Предотвращаем повторную инициализацию\n");
        sb.append("    if (window.cmpEditInitialized) return;\n");
        sb.append("    window.cmpEditInitialized = true;\n");
        sb.append("\n");
        sb.append("    console.log('cmpEdit: JavaScript library initialized');\n");
        sb.append("\n");
        sb.append("    /**\n");
        sb.append("     * Инициализация всех полей редактирования на странице\n");
        sb.append("     */\n");
        sb.append("    function initEditFields() {\n");
        sb.append("        var editFields = document.querySelectorAll('[schema=\"Edit\"]');\n");
        sb.append("        console.log('cmpEdit: Found ' + editFields.length + ' edit fields');\n");
        sb.append("        \n");
        sb.append("        for (var i = 0; i < editFields.length; i++) {\n");
        sb.append("            var field = editFields[i];\n");
        sb.append("            var name = field.getAttribute('name');\n");
        sb.append("            \n");
        sb.append("            if (name) {\n");
        sb.append("                // Добавляем обработчик изменения значения\n");
        sb.append("                field.addEventListener('change', function(e) {\n");
        sb.append("                    var input = e.target;\n");
        sb.append("                    var name = input.getAttribute('name');\n");
        sb.append("                    var value = input.value;\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие изменения\n");
        sb.append("                    var event = new CustomEvent('editChanged', {\n");
        sb.append("                        detail: { name: name, value: value },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    input.dispatchEvent(event);\n");
        sb.append("                    \n");
        sb.append("                    console.log('cmpEdit: Field \"' + name + '\" changed to:', value);\n");
        sb.append("                });\n");
        sb.append("                \n");
        sb.append("                // Добавляем обработчик ввода\n");
        sb.append("                field.addEventListener('input', function(e) {\n");
        sb.append("                    var input = e.target;\n");
        sb.append("                    var name = input.getAttribute('name');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие ввода\n");
        sb.append("                    var event = new CustomEvent('editInput', {\n");
        sb.append("                        detail: { name: name, value: input.value },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    input.dispatchEvent(event);\n");
        sb.append("                });\n");
        sb.append("                \n");
        sb.append("                // Добавляем обработчик фокуса\n");
        sb.append("                field.addEventListener('focus', function(e) {\n");
        sb.append("                    var input = e.target;\n");
        sb.append("                    var name = input.getAttribute('name');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие фокуса\n");
        sb.append("                    var event = new CustomEvent('editFocus', {\n");
        sb.append("                        detail: { name: name },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    input.dispatchEvent(event);\n");
        sb.append("                });\n");
        sb.append("                \n");
        sb.append("                // Добавляем обработчик потери фокуса\n");
        sb.append("                field.addEventListener('blur', function(e) {\n");
        sb.append("                    var input = e.target;\n");
        sb.append("                    var name = input.getAttribute('name');\n");
        sb.append("                    \n");
        sb.append("                    // Генерируем событие потери фокуса\n");
        sb.append("                    var event = new CustomEvent('editBlur', {\n");
        sb.append("                        detail: { name: name },\n");
        sb.append("                        bubbles: true\n");
        sb.append("                    });\n");
        sb.append("                    input.dispatchEvent(event);\n");
        sb.append("                });\n");
        sb.append("            }\n");
        sb.append("        }\n");
        sb.append("    }\n");
        sb.append("\n");
        sb.append("    /**\n");
        sb.append("     * Расширение D3Api для работы с cmpEdit\n");
        sb.append("     */\n");
        sb.append("    if (typeof D3Api !== 'undefined') {\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Фокусировка на поле\n");
        sb.append("         * @param {string} name - Имя поля\n");
        sb.append("         * @returns {boolean} - true если успешно\n");
        sb.append("         */\n");
        sb.append("        D3Api.focusEdit = function(name) {\n");
        sb.append("            var input = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("            if (input) {\n");
        sb.append("                input.focus();\n");
        sb.append("                return true;\n");
        sb.append("            }\n");
        sb.append("            return false;\n");
        sb.append("        };\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Очистка поля\n");
        sb.append("         * @param {string} name - Имя поля\n");
        sb.append("         * @returns {boolean} - true если успешно\n");
        sb.append("         */\n");
        sb.append("        D3Api.clearEdit = function(name) {\n");
        sb.append("            var input = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("            if (input) {\n");
        sb.append("                input.value = '';\n");
        sb.append("                \n");
        sb.append("                // Генерируем событие изменения\n");
        sb.append("                var event = new CustomEvent('editChanged', {\n");
        sb.append("                    detail: { name: name, value: '' },\n");
        sb.append("                    bubbles: true\n");
        sb.append("                });\n");
        sb.append("                input.dispatchEvent(event);\n");
        sb.append("                \n");
        sb.append("                return true;\n");
        sb.append("            }\n");
        sb.append("            return false;\n");
        sb.append("        };\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Проверка, является ли поле textarea\n");
        sb.append("         * @param {string} name - Имя поля\n");
        sb.append("         * @returns {boolean} - true если это textarea\n");
        sb.append("         */\n");
        sb.append("        D3Api.isTextArea = function(name) {\n");
        sb.append("            var input = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("            return input && input.tagName.toLowerCase() === 'textarea';\n");
        sb.append("        };\n");
        sb.append("        \n");
        sb.append("        /**\n");
        sb.append("         * Получение типа поля\n");
        sb.append("         * @param {string} name - Имя поля\n");
        sb.append("         * @returns {string|null} - Тип поля или null\n");
        sb.append("         */\n");
        sb.append("        D3Api.getEditType = function(name) {\n");
        sb.append("            var input = document.querySelector('[name=\"' + name + '\"]');\n");
        sb.append("            if (!input) return null;\n");
        sb.append("            \n");
        sb.append("            if (input.tagName.toLowerCase() === 'textarea') {\n");
        sb.append("                return 'textarea';\n");
        sb.append("            }\n");
        sb.append("            \n");
        sb.append("            return input.getAttribute('type') || 'text';\n");
        sb.append("        };\n");
        sb.append("    }\n");
        sb.append("\n");
        sb.append("    // Инициализация после загрузки DOM\n");
        sb.append("    if (document.readyState === 'loading') {\n");
        sb.append("        document.addEventListener('DOMContentLoaded', initEditFields);\n");
        sb.append("    } else {\n");
        sb.append("        initEditFields();\n");
        sb.append("    }\n");
        sb.append("})();\n");

        return sb.toString().getBytes();
    }
}